### ISSUE TITLE
yaml based example

### ISSUE THREAD

**Issue by jjangga0214** [helaili/github-graphql-action#9]
Hi, interesting action :)

YAML example would be good, rather than HCL.

**Comment by yanz-androidify** [comment]
Bug

**Comment by yanz-androidify** [comment]
Action

**Comment by yanz-androidify** [comment]
#11

**Comment by sshabu18** [comment]
I need action to my paypal :( I cannot use my funds paypal to friends and family hoecan I do ?

**Comment by helaili** [comment]
Thanks! Everything is now migrated to Actions V2 with YAML samples.
